apiVersion: v1
kind: Service
metadata:
  name: laravel-www
  annotations:
    cloud.google.com/backend-config: '{"default": "laravel-www"}'
spec:
  type: ClusterIP
  selector:
    app: laravel-www
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80